name: Clarive Kubernetes Plugin
description: Kubernetes plugin will allow you to create new pods remotely from a Clarive instance.
version: 1.0
icon: https://github.com/clarive/cla-kubernetes-plugin/public/icon/kubernetes.svg
url: https://github.com/clarive/cla-kubernetes-plugin
requires:
  - clarive_version: 6.8 <= version
dependencies:
  - cla-kubernetes-plugin
